// Placeholder data for the new UI preview. Every number here is synthetic —
// swap for real entity/dashboard service data once the design is finalized.

const RANGE_START = new Date(2025, 3, 15); // Apr 15, 2025
const RANGE_DAYS = 31; // through May 15, 2025
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

function formatDate(d) {
  return `${MONTHS[d.getMonth()]} ${d.getDate()}`;
}

// The 5 axis labels every time-series chart shows — must be an exact subset
// of the daily dates generated by risingTrend below.
export const AXIS_TICKS = ['Apr 15', 'Apr 22', 'Apr 29', 'May 6', 'May 15'];

// Generates a gently-rising trend with light noise between a start/end
// value, one point per day across the fixed Apr 15 - May 15 range so every
// data point gets a unique date label (avoids duplicate/overlapping x-axis
// ticks — see AXIS_TICKS for which of these get rendered).
function risingTrend(start, end, points = RANGE_DAYS) {
  const out = [];
  for (let i = 0; i < points; i++) {
    const t = i / (points - 1);
    const base = start + (end - start) * t;
    const noise = Math.sin(i * 1.7) * (end - start) * 0.04;
    const d = new Date(RANGE_START);
    d.setDate(d.getDate() + i);
    out.push({ date: formatDate(d), value: Math.max(0, Math.round(base + noise)) });
  }
  return out;
}

function sparkline(start, end) {
  return risingTrend(start, end, 8).map((d) => d.value);
}

export const dummyMovieOverview = {
  title: 'Movie Title',
  status: 'ON TRACK',
  releaseInDays: 18,
  releaseDateLabel: 'Release date TBD',
  dateRangeLabel: 'May 1 – May 15, 2025',

  healthScore: {
    value: 92,
    label: 'Excellent',
    deltaLabel: '8 pts vs yesterday',
    trend: risingTrend(72, 92),
  },

  kpis: [
    { key: 'buzz', label: 'Buzz', value: 93, rating: 'Excellent', deltaPct: 18, spark: sparkline(70, 93), hue: 'violet' },
    { key: 'awareness', label: 'Awareness', value: 84, rating: 'Very Good', deltaPct: 12, spark: sparkline(65, 84), hue: 'blue' },
    { key: 'sentiment', label: 'Sentiment', value: 81, rating: 'Positive', deltaPct: 5, spark: sparkline(70, 81), hue: 'green' },
    { key: 'momentum', label: 'Marketing Momentum', value: 88, rating: 'Very Good', deltaPct: 14, spark: sparkline(68, 88), hue: 'orange' },
    { key: 'reach', label: 'Regional Reach', value: 79, rating: 'Good', deltaPct: 9, spark: sparkline(62, 79), hue: 'cyan' },
    { key: 'engagement', label: 'Audience Engagement', value: 90, rating: 'Excellent', deltaPct: 16, spark: sparkline(66, 90), hue: 'indigo' },
  ],

  poster: {
    genre: 'Drama',
    language: 'English',
    runtime: '2h 15m',
    budget: 'TBD',
    distributor: 'TBD',
    format: '2D',
    releaseDate: 'TBD',
  },

  buzzOverTime: {
    totalLabel: '3.2M',
    totalCaption: 'Total Mentions',
    deltaPct: 18,
    series: risingTrend(700000, 3200000).map((d) => ({ date: d.date, value: d.value })),
  },

  sentimentOverTime: {
    positiveTotal: '2.4M',
    neutralTotal: '560K',
    negativeTotal: '240K',
    series: (() => {
      const pos = risingTrend(700000, 2400000);
      const neu = risingTrend(300000, 560000);
      const neg = risingTrend(120000, 240000);
      return pos.map((d, i) => ({
        date: d.date,
        positive: d.value,
        neutral: neu[i].value,
        negative: neg[i].value,
      }));
    })(),
  },

  topPositiveThemes: [
    { label: 'Storyline', pct: 28 },
    { label: 'Music', pct: 24 },
    { label: 'Lead Cast', pct: 18 },
    { label: 'Visuals', pct: 14 },
    { label: 'Dialogues', pct: 10 },
  ],

  insights: {
    key: {
      text: 'Positive buzz is being driven mainly by the lead cast right now. Consider leaning into character-driven content this week.',
    },
    topRegion: {
      name: 'Region A',
      deltaPct: 34,
      caption: 'Conversations vs yesterday',
    },
    biggestRisk: {
      text: 'Runtime concerns are gradually increasing. Monitor conversations closely.',
    },
  },
};
